project_id = "izqveyvcebolrqpqlmho"

[functions.clean-code]
verify_jwt = false

[functions.generate-archive]
verify_jwt = false

[functions.export-to-github]
verify_jwt = false

[functions.cleanup-storage]
verify_jwt = false
